# vim:ft=ansible:
- name: download golang binaries
  get_url: url=https://storage.googleapis.com/golang/go{{ golang.version }}.linux-amd64.tar.gz dest=/usr/local
- name: unpack golang binaries
  unarchive: src=/usr/local/go{{ golang.version }}.linux-amd64.tar.gz dest=/usr/local owner=vagrant group=vagrant copy=no
  sudo_user: root
- name: create GO HOME
  file: path=/home/vagrant/go owner=vagrant group=vagrant state=directory
  remote_user: vagrant
  sudo: False
- name: add golang ROOT
  lineinfile: dest=/home/vagrant/.bashrc line="export GOROOT=/usr/local/go" insertbefore="^#End of Paths" 
  remote_user: vagrant
  sudo: False
- name: add golang PATH
  lineinfile: dest=/home/vagrant/.bashrc line="export GOPATH=$HOME/go" insertbefore="^#End of Paths" 
  remote_user: vagrant
  sudo: False
- name: add golang ROOT bin to PATH
  lineinfile: dest=/home/vagrant/.bashrc line="export PATH=$PATH:$GOROOT/bin" insertbefore="^#End of Paths" 
  remote_user: vagrant
  sudo: False
- name: add golang PATH bin to PATH
  lineinfile: dest=/home/vagrant/.bashrc line="export PATH=$PATH:$GOPATH/bin" insertbefore="^#End of Paths" 
  remote_user: vagrant
  sudo: False
- name: source bashrc
  shell: . /home/vagrant/.bashrc
  remote_user: vagrant
  sudo: False
  #- name: go from source
  #  git: repo=https://go.googlesource.com/go dest=/usr/local/go force=yes
  #- name: change ownership og go path
  #  file: path=/usr/local/go owner=vagrant group=vagrant state=directory recurse=yes
  #- name: build golang
  #  shell: (cd /usr/local/go && git checkout go{{ golang.version}} && cd ./src && ./all.bash)

  
  
