# vim:ft=ansible:
- name: create HOME bin
  file: path=/home/vagrant/bin owner=vagrant group=vagrant state=directory
  remote_user: vagrant
  sudo: False

- name: download gimme
  get_url: dest=/home/vagrant/bin/gimme url=https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  remote_user: vagrant
  sudo: False

- name: make gimme executable
  shell: chmod +x /home/vagrant/bin/gimme
  remote_user: vagrant
  sudo: False

- name: Install go via gimme
  shell: /home/vagrant/bin/gimme {{ golang.version }}
  remote_user: vagrant
  sudo: False

- name: create GO HOME
  file: path=/home/vagrant/go owner=vagrant group=vagrant state=directory
  remote_user: vagrant
  sudo: False

- name: add golang PATH
  lineinfile: dest=/home/vagrant/.bashrc line="export GOPATH=$HOME/go" insertbefore="^#End of Paths" 
  remote_user: vagrant
  sudo: False

- name: add golang PATH bin to PATH
  lineinfile: dest=/home/vagrant/.bashrc line="export PATH=$PATH:$GOPATH/bin" insertbefore="^#End of Paths" 
  remote_user: vagrant
  sudo: False

- name: add gimme envs to the bashrc
  lineinfile: dest=/home/vagrant/.bashrc line="source ~/.gimme/envs/go{{ golang.version }}.env" insertbefore="^#End of Paths" 
  remote_user: vagrant
  sudo: False

- name: go development vimrc
  copy: src=golang.vimrc dest=/home/vagrant/.vimrc owner=vagrant group=vagrant mode=0644
  remote_user: vagrant
  sudo: False

- name: Source .bashrc
  shell: . ~/.bashrc
  remote_user: vagrant
  sudo: False
