# vim:ft=ansible:
- name: create HOME bin
  file: path=/home/vagrant/bin owner=vagrant group=vagrant state=directory
  remote_user: vagrant
  sudo: False

- name: download gimme
  get_url: dest=/home/vagrant/bin/gimme url=https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  remote_user: vagrant
  sudo: False

- name: make gimme executable
  shell: chmod +x /home/vagrant/bin/gimme
  remote_user: vagrant
  sudo: False

- name: Install go via gimme
  shell: /home/vagrant/bin/gimme {{ golang.version }}
  remote_user: vagrant
  sudo: False

- name: create GO HOME
  file: path=/home/vagrant/go owner=vagrant group=vagrant state=directory
  remote_user: vagrant
  sudo: False

- name: add golang PATH
  lineinfile: dest=/home/vagrant/.zshrc line="export GOPATH=$HOME/go" insertbefore="^#End of Paths" 
  remote_user: vagrant
  sudo: False

- name: add golang PATH bin to PATH
  lineinfile: dest=/home/vagrant/.zshrc line="export PATH=$PATH:$GOPATH/bin" insertbefore="^#End of Paths" 
  remote_user: vagrant
  sudo: False

- name: add gimme envs to the zshrc
  lineinfile: dest=/home/vagrant/.zshrc line="source ~/.gimme/envs/go{{ golang.version }}.env" insertbefore="^#End of Paths" 
  remote_user: vagrant
  sudo: False

- name: Create target directory
  file: path=/home/vagrant/.vim/ftplugin state=directory owner=vagrant

- name: go development vimrc
  copy: src=go.vim dest=/home/vagrant/.vim/ftplugin/go.vim owner=vagrant group=vagrant mode=0644
  remote_user: vagrant
  sudo: False

- name: vim-plugins
  lineinfile: dest=/home/vagrant/.vimrc line="Plugin '{{ item }}'" insertbefore="^\"End of Vundle Plugins" 
  remote_user: vagrant
  sudo: False
  with_items:
  - fatih/vim-go
