# vim:ft=ansible:
---
- hosts: all
  sudo: true
  vars:
  - nvm:
      version: v0.25.3
      node_version: '0.12'
  - vim_plugins:
    - gmarik/Vundle.vim
    - scrooloose/nerdtree
    - nanotech/jellybeans.vim
    - kristijanhusak/vim-multiple-cursors
    - tomtom/tlib_vim
    - airblade/vim-gitgutter
    - Chiel92/vim-autoformat
  roles: 
  - host
  - shell
  - c_development
  - node_development
