# vim:ft=ansible:
#
- name: vim
  apt: name=vim-nox state=present
- name: powerline
  pip: name=powerline-status
- name: vimrc
  copy: src=vim/template.vimrc dest=/home/vagrant/.vimrc owner=vagrant group=vagrant mode=0644
  remote_user: vagrant
  sudo: False
- name: vim-powerline
  lineinfile: dest=/home/vagrant/.vimrc line="source /usr/local/lib/python2.7/dist-packages/powerline/bindings/vim/plugin/powerline.vim" state=present create=yes
  remote_user: vagrant
  sudo: False
