# vim:ft=ansible:
#
# http://www.lucianofiandesio.com/vim-configuration-for-happy-java-coding
#
#

- name: JDK
  apt: name=openjdk-{{ jdk.version  }}-jdk

  
- name: Add JAVA Home
  lineinfile: dest=/home/vagrant/.bashrc line="export JAVA_HOME=/usr/lib/jvm/java-{{ jdk.version  }}-openjdk-amd64" insertbefore="^#End of Paths"
  remote_user: vagrant
  sudo: False

- name: Add Java Home path to bin path
  lineinfile: dest=/home/vagrant/.bashrc line="export PATH=$PATH:$JAVA_HOME/bin" insertbefore="^#End of Paths"
  remote_user: vagrant
  sudo: False

- name: Download Gradle
  get_url: url=https://services.gradle.org/distributions/gradle-{{ gradle.version }}-bin.zip dest=/home/vagrant/gradle-{{ gradle.version }}-bin.zip
  remote_user: vagrant
  sudo: False

- name: Create the directory for Gradle
  file: path=/usr/local/opt state=directory owner=vagrant group=vagrant mode=0755
  remote_user: vagrant
  sudo: True

- name: Unzip Gradle
  unarchive: src=/home/vagrant/gradle-{{ gradle.version }}-bin.zip dest=/usr/local/opt/ creates=yes copy=no
  remote_user: vagrant
  sudo: False

- name: Add Gradle Home
  lineinfile: dest=/home/vagrant/.bashrc line="export GRADLE_HOME=/usr/local/opt/gradle-{{ gradle.version  }}" insertbefore="^#End of Paths"
  remote_user: vagrant
  sudo: False

- name: Add Gradle Home path to bin path
  lineinfile: dest=/home/vagrant/.bashrc line="export PATH=$PATH:$GRADLE_HOME/bin" insertbefore="^#End of Paths"
  remote_user: vagrant
  sudo: False

- name: vim-plugins
  lineinfile: dest=/home/vagrant/.vimrc line="Plugin '{{ item }}'" insertbefore="^\"End of Vundle Plugins" 
  remote_user: vagrant
  sudo: False
  with_items:
    - tfnico/vim-gradle
