# vim:ft=ansible:
#
- name: nodejs
  apt: name=nodejs
- name: npm
  apt: name=npm
- name: vim-plugins
  lineinfile: dest=/home/vagrant/.vimrc line="Plugin '{{ item }}'" insertbefore="^\"End of Vundle Plugins" 
  remote_user: vagrant
  sudo: False
  with_items: 
    - moll/vim-node
    - jelera/vim-javascript-syntax
    - marijnh/tern_for_vim
    - vim-scripts/JavaScript-Indent
