# vim:ft=ansible:
---
- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/{{ nvm.version  }}/install.sh | zsh
    creates=/home/vagrant/.nvm/nvm.sh
  remote_user: vagrant
  sudo: False

- name: Install node and set version
  shell: >
    /bin/zsh -c "source ~/.nvm/nvm.sh && nvm install {{ nvm.node_version  }} && nvm alias default {{ nvm.node_version  }}"
    creates=/home/vagrant/.nvm/alias#
  remote_user: vagrant
  sudo: False

- name: node development vimrc
  copy: src=jsx.vimrc dest=/home/vagrant/.vimrc owner=vagrant group=vagrant mode=0644
  remote_user: vagrant
  sudo: False

- name: eslintrc
  copy: src=template.eslintrc dest=/home/vagrant/.eslintrc owner=vagrant group=vagrant mode=0644
  remote_user: vagrant
  sudo: False

- name: install vim plugins
  shell: >
    vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa -V
  remote_user: vagrant
  sudo: False
  register: vim_plugins

- stat: path=/vagrant/.vim/bundle/YouCompleteMe/third_party/ycmd/build.py
  register: you_complete_me

- name: initialize YouCompleteMe
  shell: >
    /bin/zsh -c "cd ~/.vim/bundle/YouCompleteMe && git submodule update --init --recursive && ./install.py --clang-completer"
  remote_user: vagrant
  sudo: False
  when: you_complete_me|changed

- name: initialize tern_for_vim
  shell: >
    /bin/zsh -c "source ~/.nvm/nvm.sh && cd ~/.vim/bundle/tern_for_vim && npm install"
  remote_user: vagrant
  sudo: False

- name: npm globals
  remote_user: vagrant
  sudo: False
  shell: >
    /bin/zsh -c "source ~/.nvm/nvm.sh && npm install -g {{ item }}"
  with_items:
    - js-beautify
    - gulp
    - nesh
    - nodemon
    - eslint
    - eslint-plugin-react
    - babel-eslint
    - mocha
