# vim:ft=ansible:
#
- stat: path=~/.nvm/nvm.sh
  register: nvm_installed

- name: Install nvm
  sudo: yes
  sudo_user: "{{ nvm.user }}"
  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version={{ nvm.version }}
  when: nvm_installed.stat.exists == False
  tags: nvm

- name: Source nvm in ~/.profile
  sudo: yes
  sudo_user: "{{ nvm.user }}"
  lineinfile: >
    dest=~/.profile
    line="source ~/.nvm/nvm.sh"
  tags: nvm

- name: Install {{ nvm.node_version }}
  command: sudo -iu {{ nvm.user }} nvm install {{ nvm.node_version }}
  register: nvm_install_result
  changed_when: "'is already installed.' not in nvm_install_result.stdout"
  tags: nvm

- name: Check if {{ nvm.node_version }} is the default node version
  shell: sudo -iu {{ nvm.user }} nvm ls | grep -e 'default -> {{ nvm.node_version }}'
  register: nvm_check_default
  changed_when: False
  ignore_errors: True
  tags: nvm

- name: Set default node version to {{ nvm.node_version }}
  command: sudo -iu {{ nvm.user }} nvm alias default {{ nvm.node_version }}
  when: nvm_check_default|failed
  tags: nvm

- name: vim-plugins
  lineinfile: dest=/home/vagrant/.vimrc line="Plugin '{{ item }}'" insertbefore="^\"End of Vundle Plugins" 
  remote_user: vagrant
  sudo: False
  with_items: 
    - moll/vim-node
    - jelera/vim-javascript-syntax
    - marijnh/tern_for_vim
    - vim-scripts/JavaScript-Indent

- name: npm globals
  remote_user: vagrant
  sudo: False
  shell: source ~/.nvm/nvm.sh && npm i -g {{ item }}
    executable=/bin/bash
  with_items:
    - js-beautify
    - "{{ npm_globals }}"

