# vim:ft=ansible:
#
- name: Create nvm directory
  file: path=/home/vagrant/.nvm state=directory owner=vagrant group=vagrant mode=0755
  remote_user: vagrant
  sudo: False
- name: Install nvm
  git: repo=https://github.com/creationix/nvm.git dest=/home/vagrant/.nvm version={{ nvm.version }}
  remote_user: vagrant
  sudo: False
- name: Source nvm in /home/vagrant/.profile
  lineinfile: dest=/home/vagrant/.profile line="source /home/vagrant/.nvm/nvm.sh" 
  remote_user: vagrant
  sudo: False
- name: Install {{ nvm.node_version }}
  command: nvm install {{ nvm.node_version }}
  remote_user: vagrant
  sudo: False
