# vim:ft=ansible:
#
- name: nodejs
  apt: name=nodejs
- name: nodejs-legacy-symlink
  apt: name=nodejs-legacy
#- name: nodejs-alias
#lineinfile: create=yes dest=/home/vagrant/.bash_aliases line="alias node='nodejs'" insertafter=EOF
- name: npm
  apt: name=npm
- name: vim-plugins
  lineinfile: dest=/home/vagrant/.vimrc line="Plugin '{{ item }}'" insertbefore="^\"End of Vundle Plugins" 
  remote_user: vagrant
  sudo: False
  with_items: 
    - moll/vim-node
    - jelera/vim-javascript-syntax
    - marijnh/tern_for_vim
    - vim-scripts/JavaScript-Indent
- name: node-alias for ubuntu
  lineinfile: dest=/home/vagrant/.bashrc line="alias node='nodejs'" insertbefore="^#End of Aliases" 
  remote_user: vagrant
  sudo: False
- name: js-beautify
  npm: name=js-beautify global=yes
