# vim:ft=ansible:
#
- name: vim
  apt: name=vim-nox state=present
- name: vimrc
  copy: src=template.vimrc dest=/home/vagrant/.vimrc owner=vagrant group=vagrant mode=0644
  remote_user: vagrant
  sudo: False
- name: vimrc
  copy: src=template.editorconfig dest=/home/vagrant/.editorconfig owner=vagrant group=vagrant mode=0644
  remote_user: vagrant
  sudo: False
- name: vim-powerline
  lineinfile: dest=/home/vagrant/.vimrc line="source /usr/local/lib/python2.7/dist-packages/powerline/bindings/vim/plugin/powerline.vim" state=present create=yes
  remote_user: vagrant
  sudo: False
- name: vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=/home/vagrant/.vim/bundle/Vundle.vim update=yes
  remote_user: vagrant
  sudo: False
