# vim:ft=ansible:
#
- name: vim
  apt: name=vim-nox state=present
- name: vimrc
  copy: src=template.vimrc dest=/home/vagrant/.vimrc owner=vagrant group=vagrant mode=0644
  remote_user: vagrant
  sudo: False
- name: vim-powerline
  lineinfile: dest=/home/vagrant/.vimrc line="source /usr/local/lib/python2.7/dist-packages/powerline/bindings/vim/plugin/powerline.vim" state=present create=yes
  remote_user: vagrant
  sudo: False
- name: git
  apt: name=git state=present
- name: vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=/home/vagrant/.vim/bundle/Vundle.vim update=yes
  remote_user: vagrant
  sudo: False
- name: vim-plugins
  lineinfile: dest=/home/vagrant/.vimrc line="Plugin '{{ item }}'" insertbefore="^\"End of Vundle Plugins" 
  remote_user: vagrant
  sudo: False
  with_items: vim_plugins
- name: vim-settings
  lineinfile: dest=/home/vagrant/.vimrc line="{{ item }}" insertbefore="^\"End of Settings" 
  remote_user: vagrant
  sudo: False
  with_items: vim_settings
